# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fe6ff0d21dcdde8c356e7c4362870c3cae6fadc0769414a384d060180b145405070cbe62c3628f54dd0e65c70bb5a91c62c07e3b50e921801b515ba83ba4a320

test:
  secret_key_base: b45b1995ae7f051a2d85ba8a45dfec0f6f5f17695e2119717d4c3cba398d9fb84919605cb3efadd01c5ddea339ba2ae6694ecb51f352155f2bbb1e0bcc7f5a92

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
